import streamlit as st
import torch
from PIL import Image
from PIL.ExifTags import TAGS
from torchvision import transforms
import timm
import datetime

# 1. PAGE CONFIG & BRANDING
st.set_page_config(page_title="Deepfake Sentinel", page_icon="🚨", layout="wide")

# CUSTOM CSS FOR POLICE THEME
st.markdown("""
    <style>
    .main { background-color: #f0f2f6; }
    .stButton>button { width: 100%; border-radius: 5px; height: 3em; background-color: #003366; color: white; }
    </style>
    """, unsafe_allow_html=True)

# 2. SIDEBAR - OFFICER INFO
with st.sidebar:
    st.image("https://upload.wikimedia.org/wikipedia/commons/1/1a/Tamil_Nadu_Police_Logo.png", width=120)
    st.title("🛡️ Forensic Portal")
    st.write("**Officer:** Ranjith (ID: TN-8821)")
    st.write(f"**Date:** {datetime.date.today()}")
    st.markdown("---")
    st.info("System Status: **Model Loaded (EfficientNet-B0)**")

# 3. HELPER FUNCTIONS
def get_metadata(image):
    info = {}
    exifdata = image.getexif()
    for tag_id in exifdata:
        tag = TAGS.get(tag_id, tag_id)
        data = exifdata.get(tag_id)
        if isinstance(data, bytes):
            data = data.decode()
        info[tag] = data
    return info

@st.cache_resource
def load_model():
    model = timm.create_model('efficientnet_b0', pretrained=False, num_classes=2)
    model.load_state_dict(torch.load('deepfake_detector.pth', map_location='cpu'))
    model.eval()
    return model

# 4. MAIN INTERFACE
st.title("🚨 Greater Chennai Police: Deepfake Forensic Lab")
st.write("Upload suspicious media for pixel-level artifact analysis and metadata verification.")

uploaded_file = st.file_uploader("📂 Drag and Drop Evidence Here", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('RGB')
    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("🖼️ Evidence Preview")
        st.image(image, use_container_width=True)
        
        # Metadata Section
        with st.expander("🔍 View File Metadata (Forensics)"):
            metadata = get_metadata(image)
            if metadata:
                for k, v in metadata.items():
                    st.write(f"**{k}:** {v}")
            else:
                st.write("No EXIF metadata found (Common in WhatsApp/Compressed images).")

    with col2:
        st.subheader("🔬 AI Analysis Results")
        
        # PREDICTION LOGIC
        transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])
        img_tensor = transform(image).unsqueeze(0)
        
        model = load_model()
        with torch.no_grad():
            output = model(img_tensor)
            probabilities = torch.nn.functional.softmax(output, dim=1)[0]
            prediction = torch.argmax(output, dim=1).item()
            conf = probabilities[prediction].item() * 100

        # DISPLAY CONFIDENCE
        if prediction == 1: # Fake
            st.error(f"⚠️ **STATUS: DEEPFAKE DETECTED**")
            st.progress(conf/100)
            st.write(f"**AI Confidence Score:** {conf:.2f}%")
        else:
            st.success(f"✅ **STATUS: AUTHENTIC IMAGE**")
            st.progress(conf/100)
            st.write(f"**AI Confidence Score:** {conf:.2f}%")

        # 5. GENERATE REPORT BUTTON
        report_text = f"""--- FORENSIC ANALYSIS REPORT ---
        Generated By: Deepfake Sentinel (TN-Police)
        Date: {datetime.datetime.now()}
        Result: {'DEEPFAKE' if prediction == 1 else 'AUTHENTIC'}
        Confidence: {conf:.2f}%
        Model: EfficientNet-B0 (Trained on Celeb-DF)
        -------------------------------"""
        
        st.download_button(
            label="📄 Download Forensic Report",
            data=report_text,
            file_name=f"Forensic_Report_{datetime.date.today()}.txt",
            mime="text/plain"
        )